

## DB config
spring:
  datasource:
    druid:
      url: jdbc:mysql://118.24.63.205:3306/athena
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true

# redis config
  redis:
    database: 0
    host: ${athena.host}
    port: 6379
    password: sl250611
    timeout: 5000
    jedis:
      pool:
        max-active: 50
        max-idle: 50
        max-wait: 10
        min-idle: 0




## mybatis config
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.iu.sl.model
server:
  port: 9090

athena:
  host: 47.96.81.112
  zookeeper: 47.96.81.112:2181
  ## kafka config
  kafka:
    consumer:
      bootstrap-servers: ${athena.host}:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: mailGroup
      auto-offset-reset: earliest
      enable-auto-commit: false
      fetch-min-size: 100
      client-id: dubbo-user
      auto-commit-interval: 500
    listener:
      ack-mode: MANUAL_IMMEDIATE
      ack-count: 10






